import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { MyContextProvider } from "../context/MyContext";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <MyContextProvider>
        <body className={"bg-cyan-950"}>
          <Header />
          <div style={{ minHeight: "calc(100vh - 112px)" }}>{children}</div>
          <Footer />
        </body>
      </MyContextProvider>
    </html>
  );
}
