import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { MyContextProvider } from "../context/MyContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <MyContextProvider>
        <body className={"bg-cyan-950"}>
          <Header />
          {children}
        </body>
      </MyContextProvider>
    </html>
  );
}
